version: "3.8"
services:
  geral-api-gtw:
    build: .
    container_name: geral-api-gtw
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/example.com.br/privkey.pem:/etc/ssl/example.com.br/privkey.pem:ro
      - /etc/letsencrypt/live/example.com.br/fullchain.pem:/etc/ssl/example.com.br/fullchain.pem:ro
      - ./config.yaml:/config.yaml:ro
    networks:
      - gateway-network
    logging:
      driver: json-file
      options:
        max-size: 100m

networks:
  gateway-network:
    name: gateway-network
    driver: bridge
